version: '3.8'

services:
  db:
    container_name: dev_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: dev_php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www
    depends_on:
      - dev_database
  nginx:
    container_name: dev_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./www:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dev_php
      - dev_database